### PR TITLE
Add travis config

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
@pcwalton Have any thoughts about this assertion fail?

**Comment by jdm** [comment]
```
     Running `/home/travis/build/servo/gaol/target/debug/file_read_all-84dc191c2e9bdbd9`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<main>' panicked at 'assertion failed: libc::read(pipe_fds[0], &mut grandchild_pid as *mut i32 as *mut c_void,
           mem::size_of::<pid_t>() as size_t) ==
    (mem::size_of::<pid_t>() as ssize_t)', platform/linux/namespace.rs:271
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by pcwalton** [comment]
Check to make sure the libc declaration is correct, maybe 32 vs 64 bits is messing us up

**Comment by nox** [comment]
@pcwalton #16 says `thread '<main>' panicked at 'assertion failed: `(left == right)` (left: `0`, right: `4`)', platform/linux/namespace.rs:271`. :(

**Comment by nox** [comment]
"PR_SET_CHILD_SUBREAPER (since Linux 3.4)", I'm afraid Travis uses a Linux kernel that does not provide that.

**Comment by Ms2ger** [comment]
#17

**Pull request closed without merging**
