### PR TITLE
Use `assert_eq!` for the `unshare()` calls so that we can figure out what error code is being returned.

### PR DESCRIPTION
**Pull request by pcwalton**
This should help us diagnose #44.

r? @jdm

### CODE REVIEW

**Comment by Eijebong** [comment]
Travis uses docker and yeah I had the same problem yesterday when I tried to run mock in a docker container. No idea how to fix it except giving CAP_SYS_ADMIN to the container which we probably can't request to travis ?

**Comment by Eijebong** [comment]
Ping on this ?

**Comment by jdm** [comment]
The answer might be to switch to taskcluster for testing if this is fundamentally incompatible with the containers that TravisCI provides.

**Comment by Eijebong** [comment]
Fixed by #50 :tada:

**Pull request closed without merging**
