### PR TITLE
Bump rand to 0.5

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by Eijebong** [comment]
Ping ? This is the last dependency using rand 0.4 in servo

**Comment by jdm** [comment]
https://github.com/servo/gaol/issues/44 is making it difficult to merge changes right now :/

**Comment by Eijebong** [comment]
Sure, anything I could do to fix this ?

**Comment by jdm** [comment]
Find someone who knows how to fix it :P

**Comment by Eijebong** [comment]
This can be merged now :tada:

**Pull request merged**
